### ISSUE TITLE
PUBGM Emulator hack developer needed! Our team will pay good amount of money.

### ISSUE THREAD

**Issue by pjthebuddy5** [guided-hacking/cfautouam#3]
@GH-Rake @KlSKE @ELTraxo @GH-iPower 
I request you guys on behalf of my team to develop a new hack for pubgm emulator. We will pay you guys a good amount of money. I hope you guys accept our request and look forward to develop a tool. It will be helpful for us and you also. I hope you reply as soon as possible.
Thank You,
Regards

**Comment by GH-Rake** [comment]
This is an issue tracker not a contact us form
